#!/usr/local/bin/python3.7

from configparser import ConfigParser
from datetime import datetime
from socket import gethostname
import logging
import csv
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('alarm', action='store', help='Alarm Text')
args = parser.parse_args()

config = ConfigParser()
config.read('/etc/glmpi.conf')
alarmfile = config.get('general', 'alarms')
logfile = config.get('general', 'logfile')

host_name = gethostname()
log = logging.getLogger(name=host_name)

log_format = logging.Formatter('%(asctime)s.%(msecs)03d %(name)s [%(levelname)s] %(threadName)s : %(message)s', '%Y-%m-%d %H:%M:%S')

log_fileh = logging.FileHandler(logfile)
log_fileh.setLevel(logging.CRITICAL)
log_fileh.setFormatter(log_format)
log.addHandler(log_fileh)


def insert_alarm(alarm):
        dt = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        Row = [str(dt), f"{alarm}"]
        log.critical(alarm)
        with open(alarmfile, mode='a') as a_file:
            alarm_writer = csv.writer(a_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
            alarm_writer.writerow(Row)


def main():
    insert_alarm(args.alarm)


if __name__ == '__main__':
    main()
